# Generated by Django 5.0.2 on 2024-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_referralcode_code_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2023-12-12'),
            preserve_default=False,
        ),
    ]
